# Generated by Django 3.0.8 on 2020-10-19 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('eq_ip', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('vendor', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('descr', models.CharField(blank=True, max_length=256, null=True)),
                ('location', models.CharField(max_length=256)),
                ('manage', models.CharField(blank=True, max_length=64, null=True)),
                ('team', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'equipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipPerformance',
            fields=[
                ('eq_pe_num', models.AutoField(primary_key=True, serialize=False)),
                ('record_date', models.DateField()),
                ('cpu_user', models.IntegerField()),
                ('memory_use', models.IntegerField()),
                ('disk_use', models.IntegerField()),
            ],
            options={
                'db_table': 'equip_performance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SnmpTraffic',
            fields=[
                ('tr_num', models.AutoField(primary_key=True, serialize=False)),
                ('eq_ip', models.CharField(max_length=64)),
                ('if_index', models.IntegerField()),
                ('tr_date', models.DateField()),
                ('in_traffic', models.TextField()),
                ('in_packet', models.TextField()),
                ('out_traffic', models.TextField()),
                ('out_packet', models.TextField()),
            ],
            options={
                'db_table': 'snmp_traffic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentSnmpsetting',
            fields=[
                ('eq_ip', models.OneToOneField(db_column='eq_ip', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.Equipment')),
                ('read_community', models.CharField(max_length=8)),
                ('write_community', models.CharField(max_length=8)),
                ('snmp_port', models.IntegerField()),
                ('snmptrap_port', models.IntegerField()),
                ('snmp_version', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'equipment_snmpsetting',
                'managed': False,
            },
        ),
    ]
