# Generated by Django 3.0.8 on 2020-11-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_authpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('codetype', models.CharField(max_length=32)),
                ('code_value', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('upper_codetype', models.CharField(blank=True, max_length=32, null=True)),
                ('upper_code', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'code',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DayPerformance',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('pr_date', models.DateTimeField()),
                ('cpu_use', models.IntegerField()),
                ('memory_use', models.IntegerField()),
                ('disk_use', models.IntegerField()),
            ],
            options={
                'db_table': 'day_performance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DayStatistics',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('index_day', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('now_in_traffic', models.TextField(blank=True, null=True)),
                ('now_in_packet', models.TextField(blank=True, null=True)),
                ('now_out_traffic', models.TextField(blank=True, null=True)),
                ('now_out_packet', models.TextField(blank=True, null=True)),
                ('max_in_traffic', models.TextField(blank=True, null=True)),
                ('max_in_packet', models.TextField(blank=True, null=True)),
                ('max_out_traffic', models.TextField(blank=True, null=True)),
                ('max_out_packet', models.TextField(blank=True, null=True)),
                ('avg_in_traffic', models.TextField(blank=True, null=True)),
                ('avg_in_packet', models.TextField(blank=True, null=True)),
                ('avg_out_traffic', models.TextField(blank=True, null=True)),
                ('avg_out_packet', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'day_statistics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipment_Code',
            fields=[
                ('eq_ip', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('vendor', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('codetype', models.CharField(max_length=32)),
                ('code_value', models.CharField(max_length=64)),
                ('descr', models.CharField(blank=True, max_length=254, null=True)),
                ('location', models.CharField(max_length=254)),
                ('manage', models.CharField(blank=True, max_length=64, null=True)),
                ('team', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'equip_code',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=64)),
                ('grade', models.CharField(max_length=64)),
                ('ev_contents', models.CharField(max_length=256)),
                ('occur', models.DateTimeField()),
                ('count', models.IntegerField()),
                ('id', models.CharField(blank=True, max_length=64, null=True)),
                ('eq_ip', models.CharField(max_length=64)),
                ('if_index', models.IntegerField()),
            ],
            options={
                'db_table': 'event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonthPerformance',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('pr_date', models.DateTimeField()),
                ('cpu_use', models.IntegerField()),
                ('memory_use', models.IntegerField()),
                ('disk_use', models.IntegerField()),
            ],
            options={
                'db_table': 'month_performance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonthStatistics',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('index_month', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('now_in_traffic', models.TextField(blank=True, null=True)),
                ('now_in_packet', models.TextField(blank=True, null=True)),
                ('now_out_traffic', models.TextField(blank=True, null=True)),
                ('now_out_packet', models.TextField(blank=True, null=True)),
                ('max_in_traffic', models.TextField(blank=True, null=True)),
                ('max_in_packet', models.TextField(blank=True, null=True)),
                ('max_out_traffic', models.TextField(blank=True, null=True)),
                ('max_out_packet', models.TextField(blank=True, null=True)),
                ('avg_in_traffic', models.TextField(blank=True, null=True)),
                ('avg_in_packet', models.TextField(blank=True, null=True)),
                ('avg_out_traffic', models.TextField(blank=True, null=True)),
                ('avg_out_packet', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'month_statistics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('no_num', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=64)),
                ('write_date', models.DateTimeField()),
                ('title', models.CharField(max_length=32)),
                ('no_contents', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'notice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NoticeReply',
            fields=[
                ('re_num', models.AutoField(primary_key=True, serialize=False)),
                ('no_num', models.IntegerField()),
                ('id', models.CharField(max_length=64)),
                ('write_date', models.DateTimeField()),
                ('no_re_num', models.IntegerField(blank=True, null=True)),
                ('re_contents', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'notice_reply',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pretreatment',
            fields=[
                ('pr_num', models.AutoField(primary_key=True, serialize=False)),
                ('index_pre', models.IntegerField()),
                ('pr_date', models.DateTimeField()),
                ('in_traffic', models.TextField()),
                ('out_traffic', models.TextField()),
                ('in_packet', models.TextField()),
                ('out_packet', models.TextField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'Pretreatment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeekPerformance',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('pr_date', models.DateTimeField()),
                ('cpu_use', models.IntegerField()),
                ('memory_use', models.IntegerField()),
                ('disk_use', models.IntegerField()),
            ],
            options={
                'db_table': 'week_performance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeekStatistics',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('index_week', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('now_in_traffic', models.TextField(blank=True, null=True)),
                ('now_in_packet', models.TextField(blank=True, null=True)),
                ('now_out_traffic', models.TextField(blank=True, null=True)),
                ('now_out_packet', models.TextField(blank=True, null=True)),
                ('max_in_traffic', models.TextField(blank=True, null=True)),
                ('max_in_packet', models.TextField(blank=True, null=True)),
                ('max_out_traffic', models.TextField(blank=True, null=True)),
                ('max_out_packet', models.TextField(blank=True, null=True)),
                ('avg_in_traffic', models.TextField(blank=True, null=True)),
                ('avg_in_packet', models.TextField(blank=True, null=True)),
                ('avg_out_traffic', models.TextField(blank=True, null=True)),
                ('avg_out_packet', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'week_statistics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YearPerformance',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('pr_date', models.DateTimeField()),
                ('cpu_use', models.IntegerField()),
                ('memory_use', models.IntegerField()),
                ('disk_use', models.IntegerField()),
            ],
            options={
                'db_table': 'year_performance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YearStatistics',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('index_year', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('now_in_traffic', models.TextField(blank=True, null=True)),
                ('now_in_packet', models.TextField(blank=True, null=True)),
                ('now_out_traffic', models.TextField(blank=True, null=True)),
                ('now_out_packet', models.TextField(blank=True, null=True)),
                ('max_in_traffic', models.TextField(blank=True, null=True)),
                ('max_in_packet', models.TextField(blank=True, null=True)),
                ('max_out_traffic', models.TextField(blank=True, null=True)),
                ('max_out_packet', models.TextField(blank=True, null=True)),
                ('avg_in_traffic', models.TextField(blank=True, null=True)),
                ('avg_in_packet', models.TextField(blank=True, null=True)),
                ('avg_out_traffic', models.TextField(blank=True, null=True)),
                ('avg_out_packet', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'year_statistics',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='interface',
            table='interface',
        ),
    ]
