# Generated by Django 3.0.8 on 2020-11-07 06:59

from django.db import migrations
import django_db_views.migration_functions
import django_db_views.operations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201107_1559'),
    ]

    operations = [
        django_db_views.operations.ViewRunPython(
            code=django_db_views.migration_functions.ForwardViewMigration("select equipment.eq_ip, vnd.name, vnd.codetype, mdl.name, mdl.codetype, equipment.descr, equipment.location,\n        equipment.name, equipment.vendor, equipment.manage, equipment.team\n        from equipment \n        left outer join code vnd on equipment.vendor = vnd.code_value\n        and vnd.codetype = 'com_vender' \n        left outer join code mdl on equipment.model = mdl.code_value\n        and mdl.codetype = 'com_model'", 'equip_code'),
            reverse_code=django_db_views.migration_functions.BackwardViewMigration('', 'equip_code'),
            atomic=False,
        ),
    ]
