# Generated by Django 3.0.8 on 2020-11-07 07:13

from django.db import migrations
import django_db_views.migration_functions
import django_db_views.operations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201107_1608'),
    ]

    operations = [
        django_db_views.operations.ViewRunPython(
            code=django_db_views.migration_functions.ForwardViewMigration("create view equip_code as\n select equipment.eq_ip, vnd.name as vnd_name, vnd.codetype as vnd_codetype, \n mdl.name as mdl_name, mdl.codetype as mdl_codetype, equipment.descr, equipment.location,\nequipment.name as equip_name, equipment.vendor, equipment.manage, equipment.team, equipment.model\n        from equipment \n        left outer join code vnd on equipment.vendor = vnd.code_value\n        and vnd.codetype = 'com_vender' \n        left outer join code mdl on equipment.model = mdl.code_value\n        and mdl.codetype = 'com_model'", 'equip_code'),
            reverse_code=django_db_views.migration_functions.BackwardViewMigration("create view equip_code as\n select equipment.eq_ip, vnd.name as vnd_name, vnd.codetype as vnd_codetype, \n mdl.name as mdl_name, mdl.codetype as mdl_codetype, equipment.descr, equipment.location,\nequipment.name as equip_name, equipment.vendor, equipment.manage, equipment.team\n        from equipment \n        left outer join code vnd on equipment.vendor = vnd.code_value\n        and vnd.codetype = 'com_vender' \n        left outer join code mdl on equipment.model = mdl.code_value\n        and mdl.codetype = 'com_model'", 'equip_code'),
            atomic=False,
        ),
    ]
