# Generated by Django 3.0.8 on 2020-11-11 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_user_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_code',
            options={'managed': False},
        ),
    ]
