# Generated by Django 3.0.8 on 2020-11-11 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201111_1702'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_code',
            table='user_code',
        ),
    ]
