# Generated by Django 3.0.8 on 2020-11-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201112_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day_Traffic',
            fields=[
                ('st_date', models.DateTimeField()),
                ('eq_ip', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('descr', models.CharField(blank=True, max_length=254, null=True)),
                ('if_index', models.IntegerField()),
                ('now_in_traffic', models.TextField(blank=True, null=True)),
                ('now_in_packet', models.TextField(blank=True, null=True)),
                ('now_out_traffic', models.TextField(blank=True, null=True)),
                ('now_out_packet', models.TextField(blank=True, null=True)),
                ('max_in_traffic', models.TextField(blank=True, null=True)),
                ('max_in_packet', models.TextField(blank=True, null=True)),
                ('max_out_traffic', models.TextField(blank=True, null=True)),
                ('max_out_packet', models.TextField(blank=True, null=True)),
                ('avg_in_traffic', models.TextField(blank=True, null=True)),
                ('avg_in_packet', models.TextField(blank=True, null=True)),
                ('avg_out_traffic', models.TextField(blank=True, null=True)),
                ('avg_out_packet', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'day_traffic',
                'managed': False,
            },
        ),
    ]
