# Generated by Django 3.0.8 on 2020-11-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_day_traffic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('eq_ip', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('tr_date', models.DateTimeField(blank=True, null=True)),
                ('in_traffic', models.TextField()),
            ],
            options={
                'db_table': 'traffic',
                'managed': False,
            },
        ),
    ]
